### ISSUE TITLE
Issues with `requirements.txt` and Compatibility on windows

### ISSUE THREAD

**Issue by 0wnway** [SakanaAI/AI-Scientist#102]
I've been struggling for the past three days trying to get this repository to work, and I'm quite frustrated. It would be really helpful to have a detailed and accurate requirements.txt file. I have Python 3.11 installed, and the current requirements.txt installs Torch 2.4. However, I've read that Torch 2.0.1 and CUDA 12.2 were used. I'm confused about how CUDA 12.2 is supposed to be compatible with Torch 2.0.1. My attempts to get this setup working have failed. Additionally, I noticed another contributor is using CUDA 11.8 with Torch 2.1.0, which seems more compatible, but I still encountered issues with `torch.compile(model)` on Windows.

Please complete the requirement.txt with the corresponding versions of the libraries used. Information about the system used and how to use it for Windows users would also save hours or days of trial and error.

**Comment by conglu1997** [comment]
Hi! All code was tested on Linux, Windows is not something we can support.
