### ISSUE TITLE
Potential Bug in perform_writeup.py

### ISSUE THREAD

**Issue by sungdukyu** [SakanaAI/AI-Scientist#105]
There's a potential bug in the prompt `citation_first_prompt` in `perform_writeup.py` on line 259. 
(Link to line: https://github.com/SakanaAI/AI-Scientist/blob/main/ai_scientist/perform_writeup.py#L259)

The prompt says,
> If there are more citations needed, add 'No more citations needed' to your thoughts

, which seems contradictory. It seems like the word "no" might have been missing, as it should perhaps read, 
> if there are **no** more citations needed, ...

This seems like a nontrivial bug in the prompt. However, looking at the example papers filled with citations, I guess the following line in the prompt (`Do not add 'No more citations needed' if you are adding citations this round.`) might have saved this bug.

BTW, the paper is awesome. Thanks for the great work!

**Comment by conglu1997** [comment]
Thank you so much for catching this!
