### ISSUE TITLE
During model learning, run Error

### ISSUE THREAD

**Issue by callor** [SakanaAI/AI-Scientist#123]
During model learning, run 
```shell
cd templates/nanoGPT && python experiment.py --out_dir run_0 && python plot.py
``` 

and then run 

```shell
python experiment.py --out_dir run_1 && python plot.py 
```
However, FileNotFoundError: [Errno 2] No such file or directory: '../../../data/shakespeare_char/train.bin' appears.
I looked at the code and saw the following part:

```py
   # nanoGPT/experiment.py line num 386
    # poor man's data loader
    if out_dir == "run_0":
        data_dir = os.path.join("../../data", dataset)
    else:
        data_dir = os.path.join("../../../data", dataset)
```
The paper results show results from run_01 to run_05, and it seems that model learning is probably repeated several times. What command should I run from the second time?

I ran it like this

```shell
cd templates/nanoGPT && python experiment.py --out_dir run_0 && python plot.py
python experiment.py --out_dir run_1 && python plot.py
python experiment.py --out_dir run_2 && python plot.py
python experiment.py --out_dir run_3 && python plot.py
python experiment.py --out_dir run_4 && python plot.py
python experiment.py --out_dir run_5 && python plot.py
```

Next week is Chuseok( Thank giving day ) in Korea. Have a happy time.

**Comment by conglu1997** [comment]
You do not need to run the experiment manually, use `launch_scientist.py`
