### ISSUE TITLE
Incorrectly generated latex file

### ISSUE THREAD

**Issue by LMJOK** [SakanaAI/AI-Scientist#128]
Why can't I generate a paper after running the code, there are only some pictures and titles, like the abstract, introduction, etc. There is no content in the paper.

**Comment by conglu1997** [comment]
Please see the FAQ:

Why has a PDF or a review not been generated?
The AI Scientist finishes an idea with a success rate that depends on both the template, the base foundation model, and the complexity of the idea. We advise referring to our main paper. The highest success rates are observed with Claude Sonnet 3.5. Reviews are best done with GPT-4o, all other models have issues with positivity bias or failure to conform to required outputs.

**Comment by LMJOK** [comment]
> Please see the FAQ:
> 
> Why has a PDF or a review not been generated? The AI Scientist finishes an idea with a success rate that depends on both the template, the base foundation model, and the complexity of the idea. We advise referring to our main paper. The highest success rates are observed with Claude Sonnet 3.5. Reviews are best done with GPT-4o, all other models have issues with positivity bias or failure to conform to required outputs.

My model, deepseek-coder-v2-0724, displays the following error. Is It related to this error?

Response Content: {"totalHits":0,"limit":10,"offset":0,"results":[]}
Error: string indices must be integers, not 'str'
Response Status Code: 200

**Comment by conglu1997** [comment]
Haven't seen that, can you uncomment the try catch and see where the error comes from?
