### ISSUE TITLE
run plot.py

### ISSUE THREAD

**Issue by NAMEKDSUN** [SakanaAI/AI-Scientist#150]
Running run.py results in an error. (ai_scientist) root@autodl-container-b97c4a8ab8-db4d211e:~/AI-Scientist/templates/nanoGPT# python plot.py /root/miniconda3/envs/ai_scientist/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice. return _methods._mean(a, axis=axis, dtype=dtype, /root/miniconda3/envs/ai_scientist/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide ret = ret.dtype.type(ret / rcount)

**Comment by conglu1997** [comment]
This is a silent warning!
