### ISSUE TITLE
final_info.json missed

### ISSUE THREAD

**Issue by JacquesGariepy** [SakanaAI/AI-Scientist#22]
Decision made: not novel after round 1
Processing idea: adaptive_block_size
Failed to evaluate idea adaptive_block_size: [Errno 2] No such file or directory: 'templates\\nanoGPT_lite\\run_0\\final_info.json'
Processing idea: random_char_perturb
Failed to evaluate idea random_char_perturb: [Errno 2] No such file or directory: 'templates\\nanoGPT_lite\\run_0\\final_info.json'
All ideas evaluated.

with open(osp.join(base_dir, "run_0", "final_info.json"), "r") as f:

**Comment by conglu1997** [comment]
Have you run the setup instructions?

**Comment by JacquesGariepy** [comment]
I run all steps

**Comment by conglu1997** [comment]
Have you run:


cd templates/nanoGPT_lite && python experiment.py --out_dir run_0 && python plot.py

**Comment by 7wik3vedi16** [comment]
![Screenshot from 2024-08-26 02-53-15](https://github.com/user-attachments/assets/a095f4d2-483d-45ce-86f7-b75ffc1ffdd4)
Error: "Feature "bf16" requires .target sm_80 or higher
