### ISSUE TITLE
Runtimeerror: python 3.11+ not yet supported for torch. compile and my torch version is 2.0.0 and 2.0.1 in ubuntu18.04

### ISSUE THREAD

**Issue by miaozujia** [SakanaAI/AI-Scientist#24]
how can i fix this error?

**Comment by rishaandesai** [comment]
Pretty sure you just need to install a previous version of Python (<=3.10)

**Comment by miaozujia** [comment]
thank you. i have solve this problem in new conda environment, including nvidia 530, cuda11.8 ,python 3.11 and pytorch 2.1.0.
