### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by wangherr** [SakanaAI/AI-Scientist#26]
Getting an LLM Generated Paper Review,
`
review = perform_review(
    paper_txt,
    model,
    client,
    num_reflections=5,
    num_fs_examples=1,
    num_reviews_ensemble=5,
    temperature=0.1,
)
`

when setting  num_fs_examples=0, 
`
review[score] = int(round(np.mean(scores)))
ValueError: cannot convert float NaN to integer
`

**Comment by conglu1997** [comment]
Hey! What model are you using? Reviewing will likely fail without GPT-4o.

**Comment by wangherr** [comment]
> Hey! What model are you using? Reviewing will likely fail without GPT-4o.

qwen-max-longcontext

the error maybe is caused of base model.

**Comment by jli113** [comment]
same here:
```
Traceback (most recent call last):
  File "/home/k1/AI-Scientist/test.py", line 11, in <module>
    review = perform_review(
             ^^^^^^^^^^^^^^^
  File "/home/k1/AI-Scientist/ai_scientist/perform_review.py", line 197, in perform_review
    review[score] = int(round(np.mean(scores)))
                        ^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

**Comment by conglu1997** [comment]
What model are you using?

**Comment by jli113** [comment]
Models weaker than GPT-4 failed to respond in proper formats, so parsed_reviews remained empty. Still the JSON formatting problem.
