### ISSUE TITLE
DualScale example paper: missing attribution for datasets

### ISSUE THREAD

**Issue by RaphaelWimmer** [SakanaAI/AI-Scientist#34]
The DualScale example paper uses two external datasets for validation ([Datasaur](https://www.research.autodesk.com/publications/same-stats-different-graphs/) and sklearn's [make_moons()](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_moons.html)) without acknowledging their origins.

https://github.com/SakanaAI/AI-Scientist/blob/04e9703920df1a571cc64371f17d4dfe456298c6/example_papers/adaptive_dual_scale_denoising/latex/template.tex#L324

**Comment by conglu1997** [comment]
Added additional attribution :)

**Comment by RaphaelWimmer** [comment]
Shouldn't this be done automatically by the AI Scientist? ;)
