### ISSUE TITLE
Got stuck during installing pdflatex

### ISSUE THREAD

**Issue by phphuc612** [SakanaAI/AI-Scientist#37]
Dear all,

While running the `sudo apt-get install texlive-full`, I cannot figure out why it got stuck but you can press and hold Enter to finish this.
I think you should note for other users.
Ref: https://askubuntu.com/questions/956006/pregenerating-context-markiv-format-this-may-take-some-time-takes-forever

Thank you for your great work.

**Comment by conglu1997** [comment]
Added a reference to this :)
