### ISSUE TITLE
Please include examples for different subjects, like archaeology or biology

### ISSUE THREAD

**Issue by Tylersuard** [SakanaAI/AI-Scientist#6]
Hello.  It would be nice to try this for research on a different field, like archaeology or biology.  You say it should be easy to modify an example for a different field, but I found it to be really difficult.  Each folder contains many files, and it is not clear how to do research on papers alone.  Would you please include an example not related to AI or coding, for example archaeology or biology?

Thank you.

**Comment by kanboura** [comment]
how to run the

**Comment by thieupu** [comment]
Indeed, we really need to know how to run your code in different fields. Also please let us know how much $ we need to generate a paper.

**Comment by conglu1997** [comment]
We have answered both questions in the FAQ!

**Comment by Tylersuard** [comment]
For others seeing this: the answer is that this code repo only works if your idea can be expressed in code.
