### ISSUE TITLE
error in plot.py 

### ISSUE THREAD

**Issue by kamatchu** [SakanaAI/AI-Scientist#83]
after running cd templates/nanoGPT && python experiment.py --out_dir run_0
and when finish i run python plot.py i get the next error

---------------
Average tokens per second: 252.49
/home/kamatchu/miniconda3/envs/ai_scientist/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/kamatchu/miniconda3/envs/ai_scientist/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

**Comment by LMJOK** [comment]
> after running cd templates/nanoGPT && python experiment.py --out_dir run_0 and when finish i run python plot.py i get the next error
> 
> Average tokens per second: 252.49 /home/kamatchu/miniconda3/envs/ai_scientist/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice. return _methods._mean(a, axis=axis, dtype=dtype, /home/kamatchu/miniconda3/envs/ai_scientist/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide ret = ret.dtype.type(ret / rcount)

Excuse me is how to solve this problem, can you give me a modified code? Thank you.
