### ISSUE TITLE
Quota exceeded instead of the exponential backoff

### ISSUE THREAD

**Issue by nouranhamdy** [SakanaAI/AI-Scientist#99]
I'm Facing this issue while trying 

python launch_scientist.py --model "gpt-4o-2024-05-13" --experiment 2d_diffusion --num-ideas 2

<img width="1636" alt="Screenshot 2024-09-03 at 2 59 49 PM" src="https://github.com/user-attachments/assets/14c08bc0-b832-43e5-9795-4d98748a0dcf">

when running the model, it seems successful

<img width="1091" alt="Screenshot 2024-09-03 at 3 20 12 PM" src="https://github.com/user-attachments/assets/5d3d4497-3480-45c3-a962-fac5df2f7bda">

**Comment by conglu1997** [comment]
Looks like you ran out of money on OpenAI.
